### ISSUE TITLE
Label shifted upward when used inside tikzcd

### ISSUE THREAD

**Issue by Leo-Schelstraete** [smimram/satex#3]
The label of a string diagram is slightly shifted upward when used inside a `tikzcd` environment:

[main.pdf](https://github.com/smimram/satex/files/14403777/main.pdf)

![image](https://github.com/smimram/satex/assets/2012073/4c01f315-539a-4d16-ba30-a7a07ef512a8)

The above was produced with the following MWE, with the command lines `pdflatex main.tex` > `satex main.satex` > `pdflatex main.tex`:

```
\documentclass{standalone}

\usepackage{tikz-cd}
\usepackage{satex}

\begin{document}
$\twocell{((1->1)["f"])}$
\begin{tikzcd}
  \twocell{((1->1)["f"])}
\end{tikzcd}
\end{document}
```

**Comment by smimram** [comment]
`satex` generates `tikzpicture` environments, so that your example is equivalent to
```latex
\begin{tikzcd}
  \begin{tikzpicture}[baseline=(current bounding box.center),yscale=-1,scale=0.5,every path/.style={join=round,cap=round},]
    \draw (0.000000,0.000000) -- (0.000000,0.500000);
    \draw (0.000000,0.500000) -- (0.000000,1.000000);
    \filldraw[fill=white] (0.000000,0.500000) ellipse (0.300000 and 0.300000);
    \draw (0.000000,0.500000) node[] {$\scriptstyle f$};
  \end{tikzpicture}
\end{tikzcd}
```
which produces the same result. I have to investigate whether there is a way of making this work. If you have ideas...

**Comment by smimram** [comment]
See https://tex.stackexchange.com/questions/483346/tikz-cd-nested-tikzpicture-wrong-center-anchor
